fig1 = tiledlayout(1,4);
% load("load_these_for_schematic_fig.mat")

% skeleton_mode changes the skeletonized image
% 2 is dilated, 3 is dilated + overlaid on im0
skeleton_mode = 3;

% 
switch skeleton_mode
    case 1
        % crop size left/bottom l1
        l1 = 1200;
    otherwise
        l1 = 1;
end


nexttile
% original image
imshow(im0(l1:end,l1:end,:))

% Create the label
annotation('textbox',[0.07 0.7 0.156 0.11],'Color',[0 0 0],...
    'VerticalAlignment','middle',...
    'String','Initial Tissue Image',...
    'HorizontalAlignment','center',...
    'FontSize',28,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);

nexttile
imshow(imEntropy)
% Create the label
annotation('textbox',[0.3 0.7 0.156 0.11],'Color',0.*[1 1 1],...
    'VerticalAlignment','middle',...
    'String','Entropy Filtered Image',...
    'HorizontalAlignment','center',...
    'FontSize',28,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);


nexttile
imshow(im1(l1:end,l1:end))
% Create the label
annotation('textbox',[0.5 0.7 0.156 0.11],'Color',[0 0 0],...
    'VerticalAlignment','middle',...
    'String','Otsu Thresholding',...
    'HorizontalAlignment','center',...
    'FontSize',28,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);


nexttile
switch skeleton_mode
    case 1
        % the original skeleton
        imshow(imSk(l1:end,l1:end))
    case 2
        % dilating the skeleton for acccessibility
        se = strel('disk', 34,4);
        imDi = imdilate(imSk, se);
        imshow(imDi(l1:end,l1:end))
    case 3
        % dilated skeleton for acccessibility
        % overlaid on original image
        se = strel('disk', 34,4);
        imDi = imdilate(imSk, se);
        imshow(imDi)
        imshowpair(imDi(l1:end,l1:end),im0(l1:end,l1:end,:))
end

% Create the label
annotation('textbox',[0.75 0.7 0.156 0.11],'Color',0.*[1 1 1],...
    'VerticalAlignment','middle',...
    'String','Skeletonized Image',...
    'HorizontalAlignment','center',...
    'FontSize',28,...
    'FontName','Times New Roman',...
    'FitBoxToText','off',...
    'BackgroundColor',[1 1 1]);


% Create arrow 1
annotation('textarrow',[0.24 0.28],...
    [0.52 0.52],'LineWidth',20,'HeadWidth',50,...
    'HeadLength',30);

% Create arrow 2
annotation('textarrow',[0.48 0.52],...
    [0.52 0.52],'LineWidth',20,'HeadWidth',50,...
    'HeadLength',30);

% Create arrow 3
annotation('textarrow',[0.72 0.76],...
    [0.52 0.52],'LineWidth',20,'HeadWidth',50,...
    'HeadLength',30);


% The schematic shows our process for producing the centerlines for the
% tissue which we use for calculating the tissue width and length. First,
% we apply an entropy filter using a structuring element of $5 \mu m$ to
% the image to prepare the image for binarization. Then, we use the default
% thresholding algorithm on MATLAB (Otsu) to binazrize the image. Lastly,
% we skeletonize the image to extract the tissue centerlines. The images
% shown here are zoomed in to show details and help with visibility of the centerlines. 


